const fs = require('fs-extra');
const path = require('path');
const glob = require('glob');
const matter = require('gray-matter');

const docsRoot = path.join(__dirname, '../docs');
const sidebarPath = path.join(__dirname, '../sidebars.js');

function generateSidebar() {
  const categories = {};

  // Find all markdown files in the docs directory
  const files = glob.sync('**/*.md', { cwd: docsRoot });

  files.forEach((file) => {
    const filePath = path.join(docsRoot, file);
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const { data: frontmatter } = matter(fileContent);
    const docId = file.replace(/\.md$/, '');

    // Skip files without a category in frontmatter
    if (!frontmatter.category) {
      return;
    }

    const categoryLabel = frontmatter.category;
    if (!categories[categoryLabel]) {
      categories[categoryLabel] = {
        type: 'category',
        label: categoryLabel,
        items: [],
        // Store category-level metadata if needed, e.g., from a _category_.json file
        collapsed:
          frontmatter.collapsed !== undefined ? frontmatter.collapsed : true,
        position:
          frontmatter.position !== undefined ? frontmatter.position : Infinity,
      };
    }

    categories[categoryLabel].items.push({
      id: docId,
      position: frontmatter.sidebar_position || Infinity,
    });
  });

  // Sort docs within each category by sidebar_position
  for (const key in categories) {
    categories[key].items.sort((a, b) => a.position - b.position);
    // Remove the temporary position property before writing to file
    categories[key].items = categories[key].items.map((item) => item.id);
  }

  // Sort categories by their position
  const sortedCategories = Object.values(categories).sort(
    (a, b) => a.position - b.position,
  );

  const sidebarContent = `/**
 * This file is auto-generated by a script. Do not edit it manually.
 * To add or remove docs, simply add or remove files in the docs/ folder.
 * To customize the sidebar, edit the frontmatter of your docs files.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  godmode: ${JSON.stringify(sortedCategories, null, 2)},
};

module.exports = sidebars;
`;

  fs.writeFileSync(sidebarPath, sidebarContent);
  console.log('✅ Sidebars generated successfully!');
}

try {
  generateSidebar();
} catch (error) {
  console.error('❌ Error generating sidebars:', error);
  process.exit(1);
}
